import Header from "../components/Header";
import Footer from "../components/Footer";
import { Inter } from 'next/font/google';
import "./globals.css";
import { AppWrapper } from "@/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SweetShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <AppWrapper>
          <Header />
          {children}
          <Footer />
        </AppWrapper>
      </body>
    </html>
  );
}


